name: trust_core
description: On-device single function face detection library using Google ML Kit.
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_image_labeling: ^0.13.0
  geolocator: ^11.0.0
  permission_handler: ^11.4.0
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
