name: trust_core
description: On-device face registration & verification library using Google ML Kit.
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.12.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^11.4.0
  image: ^4.5.3
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
